name: "Slack Message Scheduler"
description: "Schedules messages from the files specified in message-file"
inputs:
  slack-user-oauth-access-token:
    description: "User OAuth access token"
    required: true
runs:
  using: "node16"  
  main: "dist/index.js"