name: "AI Conference Reminder"
description: "Send messages into slack based on conferences.json"
inputs:
  slack-user-oauth-access-token:
    description: "User OAuth access token"
    required: true
  slack-channel:
    description: "Channel ID"
    required: true
  git-repository:
    description: "Git repository URL"
    required: true
runs:
  using: "node16"  
  main: "dist/index.js"
